version: '3.8'
services:
  api-protheus:
    container_name: api_protheus
    build: .
    volumes:
      - vol_api_protheus:/app
    ports:
      - "${API_HOST}:${API_PORT}:5000"
    restart: always

volumes:
  vol_api_protheus:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH_APP}
  vol_api_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH_LOGS}
