version: '3.7'
services:
  api-protheus:
    container_name: api_protheus
    build: .
    volumes:
      - vol_api_protheus:/app
    ports:
      # Escrever na mão pq o .env não é carregado no momento que o Docker Compose passa no `ports`.
      - "192.168.17.24:9000:9000"
    restart: always
    # Flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT

volumes:
  vol_api_protheus:
    name: vol_api_protheus
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH_APP}
